services:
  php:
    extends:
      file: compose.yml
      service: php
    ports:
      - ${DOCKER_SERVE_PORT}:8000
      - ${DOCKER_VITE_PORT}:5173
  db:
    extends:
      file: compose.yml
      service: db
  redis:
    extends:
      file: compose.yml
      service: redis
  elasticsearch:
    extends:
      file: compose.yml
      service: elasticsearch
  elasticsearch-init:
    extends:
      file: compose.yml
      service: elasticsearch-init
    environment:
      - ELASTICSEARCH_PASSWORD=local123
  kibana:
    extends:
      file: compose.yml
      service: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      # Password hardcodata per ambiente local (deve corrispondere a ELASTIC_PASSWORD)
      - ELASTICSEARCH_PASSWORD=local123
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      # Rimossi SERVER_BASEPATH e SERVER_REWRITEBASEPATH per accesso diretto in local
    ports:
      - ${DOCKER_KIBANA_PORT:-5601}:5601
  minio:
    image: "minio/minio:latest"
    container_name: "minio-${APP_NAME}"
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-laravel}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-laravelminio}
      CONSOLE_BASE_HREF: "/minio"
    command: 'minio server /data/minio --console-address ":8900"'
    platform: linux/amd64
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
    volumes:
      - "./docker/volumes/minio/data:/data/minio"
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      retries: 3
      timeout: 5s
  horizon:
    extends:
      file: compose.yml
      service: horizon
  mailpit:
    container_name: "mailpit-${APP_NAME}"
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
