services:
  php:
    extends:
      file: develop.compose.yml
      service: php
  db:
    extends:
      file: develop.compose.yml
      service: db
  redis:
    extends:
      file: develop.compose.yml
      service: redis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: "elasticsearch-${APP_NAME}"
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      # Password hardcodata per ambiente local
      - ELASTIC_PASSWORD=local123
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: "kibana-${APP_NAME}"
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      # Password hardcodata per ambiente local (deve corrispondere a ELASTIC_PASSWORD)
      - ELASTICSEARCH_PASSWORD=local123
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      # Rimossi SERVER_BASEPATH e SERVER_REWRITEBASEPATH per accesso diretto in local
    ports:
      - ${DOCKER_KIBANA_PORT:-5601}:5601
  minio:
    extends:
      file: develop.compose.yml
      service: minio
  mailpit:
    extends:
      file: develop.compose.yml
      service: mailpit

